[package]
name = "roland-rds-derive"
version = "0.9.3"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.29"
quote = "1.0.33"
proc-macro2 = "1.0.66"