[package]
name = "roland-rds-derive"
version = "0.3.0"
edition = "2021"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
